# Eliza Teplow - Project Proposal and Data Sources

## Predicting Boston Housing Values using Property and Neighborhood Characteristics

### Part 1

**Problem:** 
Housing prices vary substantially throughout the city of Boston. A property's value can be related to characteristics of the property itself, like square footage, number of bedrooms, and amenities, or related to the location and neighborhood where the property is located. We can use data science to help identify which characteristics are most strongly associated with property values and determine whether those characteristics can be used to predict the value of a home.

**Key Questions of Interest:**

**1)** Which property and neighborhood characteristics have the strongest association with property values in Boston?

**2)** How accurately can a property's estimated value be predicted using characteristics related to the property?

**Additional Interesting Questions:**
- How much variation in Boston property values is associated with the neighborhood compared to the characteristics of the property?

### Part 2 - State Source and Load Data

**Data Source:** The data for this project comes from the City of Boston's 'Analyze Boston' data hub and contains property assessment information for properties in Boston. I accessed the data using the CKAN Data API provided on the website (https://data.boston.gov/dataset/property-assessment/resource/ee73430d-96c0-423e-ad21-c4cfb54c8961).

In [5]:
import urllib.request
import json
import pandas as pd

all_records = []
resource_id = "ee73430d-96c0-423e-ad21-c4cfb54c8961"
limit = 1000
offset = 0

while True:  
    url = (
    "https://data.boston.gov/api/3/action/datastore_search"
    f"?resource_id={resource_id}&limit={limit}&offset={offset}")

    with urllib.request.urlopen(url) as response:   
        data = json.load(response)

    records = data["result"]["records"]

    if len(records) == 0:
        break

    all_records.extend(records)

    offset += limit 

df = pd.DataFrame(all_records)

In [6]:
df.head()

,_id,PID,CM_ID,GIS_ID,ST_NUM,ST_ALPHA,ST_NUM2,ST_NAME,UNIT_NUM,CITY,...,KITCHEN_STYLE2,KITCHEN_STYLE3,HEAT_TYPE,HEAT_SYSTEM,AC_TYPE,FIREPLACES,ORIENTATION,NUM_PARKING,PROP_VIEW,CORNER_UNIT
0,1,0100001000,None,0100001000,195,None,None,Lexington ST,None,EAST BOSTON,...,S - Semi-Modern,S - Semi-Modern,W - Ht Water/Steam,None,N - None,0,None,3,A - Average,None
1,2,0100002000,None,0100002000,197,None,None,Lexington ST,None,EAST BOSTON,...,M - Modern,M - Modern,F - Forced Hot Air,None,C - Central AC,0,None,0,A - Average,None
2,3,0100003000,None,0100003000,199,None,None,Lexington ST,None,EAST BOSTON,...,S - Semi-Modern,S - Semi-Modern,S - Space Heat,None,N - None,0,None,0,A - Average,None
3,4,0100004000,None,0100004000,201,None,None,Lexington ST,None,EAST BOSTON,...,S - Semi-Modern,S - Semi-Modern,W - Ht Water/Steam,None,N - None,0,None,0,A - Average,None
4,5,0100005000,None,0100005000,203,None,None,Lexington ST,None,EAST BOSTON,...,N - No Remodeling,S - Semi-Modern,W - Ht Water/Steam,None,N - None,0,None,0,A - Average,None

In [7]:
print(df.shape)
print(df.columns)

(184552, 68)
Index(['_id', 'PID', 'CM_ID', 'GIS_ID', 'ST_NUM', 'ST_ALPHA', 'ST_NUM2',
       'ST_NAME', 'UNIT_NUM', 'CITY', 'ZIP_CODE', 'BLDG_SEQ', 'NUM_BLDGS',
       'LUC', 'LU', 'LU_DESC', 'BLDG_TYPE', 'OWN_OCC', 'OWNER',
       'MAIL_ADDRESSEE', 'MAIL_STREET_ADDRESS', 'MAIL_CITY', 'MAIL_STATE',
       'MAIL_ZIP_CODE', 'RES_FLOOR', 'CD_FLOOR', 'RES_UNITS', 'COM_UNITS',
       'RC_UNITS', 'LAND_SF', 'GROSS_AREA', 'LIVING_AREA', 'LAND_VALUE',
       'BLDG_VALUE', 'SFYI_VALUE', 'TOTAL_VALUE', 'GROSS_TAX', 'YR_BUILT',
       'YR_REMODEL', 'STRUCTURE_CLASS', 'ROOF_STRUCTURE', 'ROOF_COVER',
       'INT_WALL', 'EXT_FNISHED', 'INT_COND', 'EXT_COND', 'OVERALL_COND',
       'BED_RMS', 'FULL_BTH', 'HLF_BTH', 'KITCHENS', 'TT_RMS', 'BDRM_COND',
       'BTHRM_STYLE1', 'BTHRM_STYLE2', 'BTHRM_STYLE3', 'KITCHEN_TYPE',
       'KITCHEN_STYLE1', 'KITCHEN_STYLE2', 'KITCHEN_STYLE3', 'HEAT_TYPE',
       'HEAT_SYSTEM', 'AC_TYPE', 'FIREPLACES', 'ORIENTATION', 'NUM_PARKING',
       'PROP_VIEW', 'CORNER_UNIT'],
      dtype='object')

In [8]:
housing_df = df[["TOTAL_VALUE", "LIVING_AREA", "LAND_VALUE", "LAND_SF", "BED_RMS",
                 "FULL_BTH", "TT_RMS", "YR_BUILT", "YR_REMODEL", "NUM_PARKING",
                 "FIREPLACES", "CITY", "ZIP_CODE", "LU_DESC", "BLDG_TYPE",
                 "OVERALL_COND", "AC_TYPE", "HEAT_TYPE", "PROP_VIEW"]].copy()

housing_df.head()

,TOTAL_VALUE,LIVING_AREA,LAND_VALUE,LAND_SF,BED_RMS,FULL_BTH,TT_RMS,YR_BUILT,YR_REMODEL,NUM_PARKING,FIREPLACES,CITY,ZIP_CODE,LU_DESC,BLDG_TYPE,OVERALL_COND,AC_TYPE,HEAT_TYPE,PROP_VIEW
0,"822,900",2202,"193,800","1,150",6,3,12,1900,None,3,0,EAST BOSTON,02128,THREE-FAM DWELLING,RE - Row End,A - Average,N - None,W - Ht Water/Steam,A - Average
1,"868,400",2307,"198,300","1,150",3,3,9,1920,2000,0,0,EAST BOSTON,02128,THREE-FAM DWELLING,RM - Row Middle,A - Average,C - Central AC,F - Forced Hot Air,A - Average
2,"840,300",2268,"203,400","1,150",5,3,13,1905,1985,0,0,EAST BOSTON,02128,THREE-FAM DWELLING,RM - Row Middle,A - Average,N - None,S - Space Heat,A - Average
3,"797,300",2028,"209,400","1,150",5,3,11,1900,1991,0,0,EAST BOSTON,02128,THREE-FAM DWELLING,RM - Row Middle,A - Average,N - None,W - Ht Water/Steam,A - Average
4,"844,400",2546,"266,200","2,010",6,3,13,1900,1978,0,0,EAST BOSTON,02128,THREE-FAM DWELLING,RE - Row End,A - Average,N - None,W - Ht Water/Steam,A - Average

In [9]:
numeric = ["TOTAL_VALUE", "LIVING_AREA", "LAND_VALUE", "LAND_SF", "BED_RMS", 
           "FULL_BTH", "TT_RMS", "YR_BUILT", "YR_REMODEL", "NUM_PARKING", 
           "FIREPLACES"]

for x in numeric:
    housing_df[x] = housing_df[x].str.replace(",", "")
    housing_df[x] = pd.to_numeric(housing_df[x])

In [10]:
categorical = ["CITY", "ZIP_CODE", "LU_DESC", "OVERALL_COND", "AC_TYPE", 
               "HEAT_TYPE", "BLDG_TYPE", "PROP_VIEW"]

for x in categorical:
    housing_df[x] = housing_df[x].astype("category")

In [11]:
print(housing_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 184552 entries, 0 to 184551
Data columns (total 19 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   TOTAL_VALUE   184552 non-null  int64
 1   LIVING_AREA   150243 non-null  float64
 2   LAND_VALUE    184552 non-null  int64
 3   LAND_SF       176456 non-null  float64
 4   BED_RMS       135643 non-null  float64
 5   FULL_BTH      171767 non-null  float64
 6   TT_RMS        135569 non-null  float64
 7   YR_BUILT      161992 non-null  float64
 8   YR_REMODEL    89104 non-null   float64
 9   NUM_PARKING   135808 non-null  float64
 10  FIREPLACES    172158 non-null  float64
 11  CITY          184549 non-null  category
 12  ZIP_CODE      184548 non-null  category
 13  LU_DESC       184552 non-null  category
 14  BLDG_TYPE     181184 non-null  category
 15  OVERALL_COND  174159 non-null  category
 16  AC_TYPE       136127 non-null  category
 17  HEAT_TYPE     136157 non-null  category
 18  PROP_VIEW     137705 non-null  category
dtypes: category(8), float64(9), int64(2)
memory usage: 17.3 MB
None

### Part 3 - How this data will answer my questions

The Boston property assessment data will be used to look at how different property and location characteristics relate to the property values. To answer my first question, I will analyze the relationships between property value and characteristics such as location, living area, number of bedrooms and bathrooms, property type, age, and overall condition to identify which features have the strongest associations with value. For my second question, I will use machine learning to predict property value based on the characteristics provided in the dataset. I can then compare the predicted values to the actual values to evaluate how accurately the model can estimate property values in Boston.

### Part 4 - Video Import

In [25]:
from IPython.display import Video

Video("project_video.mp4", embed=True)